--
-- PostgreSQL database dump
--

\restrict gXJ3tiWlPMaYV9DZIKmD6l84xoB37yCuYCSLYJzc7NduxdhUiwXo9Sbixm1IAzp

-- Dumped from database version 16.15
-- Dumped by pg_dump version 16.15

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: accounts_address; Type: TABLE; Schema: public; Owner: ai_store_user
--

CREATE TABLE public.accounts_address (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    phone character varying(15),
    pincode character varying(10) NOT NULL,
    locality character varying(200),
    address_line character varying(255) NOT NULL,
    city character varying(100) NOT NULL,
    state character varying(50) NOT NULL,
    landmark character varying(200),
    address_type character varying(10) NOT NULL,
    is_default boolean NOT NULL,
    latitude numeric(10,7),
    longitude numeric(10,7),
    area character varying(200),
    formatted_address text,
    slug character varying(50) NOT NULL,
    user_id bigint
);


ALTER TABLE public.accounts_address OWNER TO ai_store_user;

--
-- Name: accounts_address_id_seq; Type: SEQUENCE; Schema: public; Owner: ai_store_user
--

ALTER TABLE public.accounts_address ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_address_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: accounts_customuser; Type: TABLE; Schema: public; Owner: ai_store_user
--

CREATE TABLE public.accounts_customuser (
    id bigint NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL,
    email character varying(254) NOT NULL,
    is_activated boolean NOT NULL,
    is_email_verified boolean NOT NULL,
    otp_created_at timestamp with time zone,
    temp_otp character varying(6)
);


ALTER TABLE public.accounts_customuser OWNER TO ai_store_user;

--
-- Name: accounts_customuser_groups; Type: TABLE; Schema: public; Owner: ai_store_user
--

CREATE TABLE public.accounts_customuser_groups (
    id bigint NOT NULL,
    customuser_id bigint NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.accounts_customuser_groups OWNER TO ai_store_user;

--
-- Name: accounts_customuser_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: ai_store_user
--

ALTER TABLE public.accounts_customuser_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_customuser_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: accounts_customuser_id_seq; Type: SEQUENCE; Schema: public; Owner: ai_store_user
--

ALTER TABLE public.accounts_customuser ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_customuser_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: accounts_customuser_user_permissions; Type: TABLE; Schema: public; Owner: ai_store_user
--

CREATE TABLE public.accounts_customuser_user_permissions (
    id bigint NOT NULL,
    customuser_id bigint NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.accounts_customuser_user_permissions OWNER TO ai_store_user;

--
-- Name: accounts_customuser_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: ai_store_user
--

ALTER TABLE public.accounts_customuser_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_customuser_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: accounts_profile; Type: TABLE; Schema: public; Owner: ai_store_user
--

CREATE TABLE public.accounts_profile (
    id bigint NOT NULL,
    phone character varying(15),
    profile_picture character varying(100),
    slug character varying(50) NOT NULL,
    name_id bigint NOT NULL
);


ALTER TABLE public.accounts_profile OWNER TO ai_store_user;

--
-- Name: accounts_profile_id_seq; Type: SEQUENCE; Schema: public; Owner: ai_store_user
--

ALTER TABLE public.accounts_profile ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_profile_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: accounts_wishlist; Type: TABLE; Schema: public; Owner: ai_store_user
--

CREATE TABLE public.accounts_wishlist (
    id bigint NOT NULL,
    created_at timestamp with time zone,
    slug character varying(50) NOT NULL,
    product_id bigint NOT NULL,
    user_id bigint
);


ALTER TABLE public.accounts_wishlist OWNER TO ai_store_user;

--
-- Name: accounts_wishlist_id_seq; Type: SEQUENCE; Schema: public; Owner: ai_store_user
--

ALTER TABLE public.accounts_wishlist ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_wishlist_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: ai_store_user
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO ai_store_user;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: ai_store_user
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: ai_store_user
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO ai_store_user;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: ai_store_user
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: ai_store_user
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO ai_store_user;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: ai_store_user
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: authtoken_token; Type: TABLE; Schema: public; Owner: ai_store_user
--

CREATE TABLE public.authtoken_token (
    key character varying(40) NOT NULL,
    created timestamp with time zone NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.authtoken_token OWNER TO ai_store_user;

--
-- Name: cart_cart; Type: TABLE; Schema: public; Owner: ai_store_user
--

CREATE TABLE public.cart_cart (
    id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL,
    slug character varying(255) NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.cart_cart OWNER TO ai_store_user;

--
-- Name: cart_cart_id_seq; Type: SEQUENCE; Schema: public; Owner: ai_store_user
--

ALTER TABLE public.cart_cart ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cart_cart_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: cart_cartitem; Type: TABLE; Schema: public; Owner: ai_store_user
--

CREATE TABLE public.cart_cartitem (
    id bigint NOT NULL,
    quantity integer NOT NULL,
    slug character varying(255) NOT NULL,
    cart_id bigint NOT NULL,
    product_id bigint NOT NULL,
    CONSTRAINT cart_cartitem_quantity_check CHECK ((quantity >= 0))
);


ALTER TABLE public.cart_cartitem OWNER TO ai_store_user;

--
-- Name: cart_cartitem_id_seq; Type: SEQUENCE; Schema: public; Owner: ai_store_user
--

ALTER TABLE public.cart_cartitem ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.cart_cartitem_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: chat_conversation; Type: TABLE; Schema: public; Owner: ai_store_user
--

CREATE TABLE public.chat_conversation (
    id bigint NOT NULL,
    status character varying(20) NOT NULL,
    slug character varying(100),
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.chat_conversation OWNER TO ai_store_user;

--
-- Name: chat_conversation_id_seq; Type: SEQUENCE; Schema: public; Owner: ai_store_user
--

ALTER TABLE public.chat_conversation ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.chat_conversation_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: chat_message; Type: TABLE; Schema: public; Owner: ai_store_user
--

CREATE TABLE public.chat_message (
    id bigint NOT NULL,
    message text NOT NULL,
    is_read boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    conversation_id bigint NOT NULL,
    sender_id bigint NOT NULL
);


ALTER TABLE public.chat_message OWNER TO ai_store_user;

--
-- Name: chat_message_id_seq; Type: SEQUENCE; Schema: public; Owner: ai_store_user
--

ALTER TABLE public.chat_message ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.chat_message_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: coupons_coupon; Type: TABLE; Schema: public; Owner: ai_store_user
--

CREATE TABLE public.coupons_coupon (
    id bigint NOT NULL,
    code character varying(50) NOT NULL,
    description text NOT NULL,
    discount_type character varying(20) NOT NULL,
    discount_value numeric(10,2) NOT NULL,
    minimum_order_amount numeric(10,2) NOT NULL,
    maximum_discount_amount numeric(10,2),
    valid_from timestamp with time zone NOT NULL,
    valid_until timestamp with time zone NOT NULL,
    usage_limit integer,
    used_count integer NOT NULL,
    per_user_limit integer,
    weekly_user_limit integer NOT NULL,
    is_active boolean NOT NULL,
    slug character varying(100) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT coupons_coupon_per_user_limit_check CHECK ((per_user_limit >= 0)),
    CONSTRAINT coupons_coupon_usage_limit_check CHECK ((usage_limit >= 0)),
    CONSTRAINT coupons_coupon_used_count_check CHECK ((used_count >= 0)),
    CONSTRAINT coupons_coupon_weekly_user_limit_check CHECK ((weekly_user_limit >= 0))
);


ALTER TABLE public.coupons_coupon OWNER TO ai_store_user;

--
-- Name: coupons_coupon_id_seq; Type: SEQUENCE; Schema: public; Owner: ai_store_user
--

ALTER TABLE public.coupons_coupon ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.coupons_coupon_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: coupons_couponconfiguration; Type: TABLE; Schema: public; Owner: ai_store_user
--

CREATE TABLE public.coupons_couponconfiguration (
    id bigint NOT NULL,
    weekly_user_limit integer NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    CONSTRAINT coupons_couponconfiguration_weekly_user_limit_check CHECK ((weekly_user_limit >= 0))
);


ALTER TABLE public.coupons_couponconfiguration OWNER TO ai_store_user;

--
-- Name: coupons_couponconfiguration_id_seq; Type: SEQUENCE; Schema: public; Owner: ai_store_user
--

ALTER TABLE public.coupons_couponconfiguration ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.coupons_couponconfiguration_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: coupons_couponusage; Type: TABLE; Schema: public; Owner: ai_store_user
--

CREATE TABLE public.coupons_couponusage (
    id bigint NOT NULL,
    discount_amount numeric(10,2) NOT NULL,
    used_at timestamp with time zone NOT NULL,
    slug character varying(150) NOT NULL,
    coupon_id bigint NOT NULL,
    order_id bigint NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.coupons_couponusage OWNER TO ai_store_user;

--
-- Name: coupons_couponusage_id_seq; Type: SEQUENCE; Schema: public; Owner: ai_store_user
--

ALTER TABLE public.coupons_couponusage ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.coupons_couponusage_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: ai_store_user
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id bigint NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO ai_store_user;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: ai_store_user
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: ai_store_user
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO ai_store_user;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: ai_store_user
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: ai_store_user
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO ai_store_user;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: ai_store_user
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: ai_store_user
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO ai_store_user;

--
-- Name: order_order; Type: TABLE; Schema: public; Owner: ai_store_user
--

CREATE TABLE public.order_order (
    id bigint NOT NULL,
    order_number character varying(30) NOT NULL,
    slug character varying(100) NOT NULL,
    status character varying(20) NOT NULL,
    total_amount numeric(12,2) NOT NULL,
    discount_amount numeric(12,2) NOT NULL,
    shipping_name character varying(100) NOT NULL,
    shipping_phone character varying(20) NOT NULL,
    shipping_city character varying(100) NOT NULL,
    shipping_pincode character varying(10) NOT NULL,
    shipping_address text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    coupon_id bigint,
    user_id bigint NOT NULL
);


ALTER TABLE public.order_order OWNER TO ai_store_user;

--
-- Name: order_order_id_seq; Type: SEQUENCE; Schema: public; Owner: ai_store_user
--

ALTER TABLE public.order_order ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.order_order_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: order_orderitem; Type: TABLE; Schema: public; Owner: ai_store_user
--

CREATE TABLE public.order_orderitem (
    id bigint NOT NULL,
    quantity integer NOT NULL,
    price numeric(10,2) NOT NULL,
    slug character varying(150) NOT NULL,
    order_id bigint NOT NULL,
    variant_id bigint NOT NULL,
    CONSTRAINT order_orderitem_quantity_check CHECK ((quantity >= 0))
);


ALTER TABLE public.order_orderitem OWNER TO ai_store_user;

--
-- Name: order_orderitem_id_seq; Type: SEQUENCE; Schema: public; Owner: ai_store_user
--

ALTER TABLE public.order_orderitem ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.order_orderitem_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: payment_payment; Type: TABLE; Schema: public; Owner: ai_store_user
--

CREATE TABLE public.payment_payment (
    id bigint NOT NULL,
    payment_method character varying(20) NOT NULL,
    transaction_id character varying(255),
    amount numeric(10,2) NOT NULL,
    status character varying(20) NOT NULL,
    paid_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    slug character varying(150) NOT NULL,
    order_id bigint NOT NULL,
    user_id bigint NOT NULL,
    currency character varying(10) NOT NULL,
    gateway_order_id character varying(255),
    gateway_payment_id character varying(255),
    gateway_signature text
);


ALTER TABLE public.payment_payment OWNER TO ai_store_user;

--
-- Name: payment_payment_id_seq; Type: SEQUENCE; Schema: public; Owner: ai_store_user
--

ALTER TABLE public.payment_payment ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.payment_payment_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: products_category; Type: TABLE; Schema: public; Owner: ai_store_user
--

CREATE TABLE public.products_category (
    id bigint NOT NULL,
    name character varying(100) NOT NULL,
    slug character varying(120) NOT NULL
);


ALTER TABLE public.products_category OWNER TO ai_store_user;

--
-- Name: products_category_id_seq; Type: SEQUENCE; Schema: public; Owner: ai_store_user
--

ALTER TABLE public.products_category ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.products_category_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: products_color; Type: TABLE; Schema: public; Owner: ai_store_user
--

CREATE TABLE public.products_color (
    id bigint NOT NULL,
    name character varying(50) NOT NULL,
    hex_code character varying(7) NOT NULL,
    slug character varying(80) NOT NULL
);


ALTER TABLE public.products_color OWNER TO ai_store_user;

--
-- Name: products_color_id_seq; Type: SEQUENCE; Schema: public; Owner: ai_store_user
--

ALTER TABLE public.products_color ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.products_color_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: products_product; Type: TABLE; Schema: public; Owner: ai_store_user
--

CREATE TABLE public.products_product (
    id bigint NOT NULL,
    name character varying(200) NOT NULL,
    slug character varying(220) NOT NULL,
    image character varying(100),
    description text NOT NULL,
    brand character varying(100) NOT NULL,
    is_active boolean NOT NULL,
    created_at timestamp with time zone
);


ALTER TABLE public.products_product OWNER TO ai_store_user;

--
-- Name: products_product_cat; Type: TABLE; Schema: public; Owner: ai_store_user
--

CREATE TABLE public.products_product_cat (
    id bigint NOT NULL,
    product_id bigint NOT NULL,
    category_id bigint NOT NULL
);


ALTER TABLE public.products_product_cat OWNER TO ai_store_user;

--
-- Name: products_product_cat_id_seq; Type: SEQUENCE; Schema: public; Owner: ai_store_user
--

ALTER TABLE public.products_product_cat ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.products_product_cat_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: products_product_id_seq; Type: SEQUENCE; Schema: public; Owner: ai_store_user
--

ALTER TABLE public.products_product ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.products_product_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: products_productimage; Type: TABLE; Schema: public; Owner: ai_store_user
--

CREATE TABLE public.products_productimage (
    id bigint NOT NULL,
    image character varying(100) NOT NULL,
    alt_text character varying(150) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    product_id bigint NOT NULL
);


ALTER TABLE public.products_productimage OWNER TO ai_store_user;

--
-- Name: products_productimage_id_seq; Type: SEQUENCE; Schema: public; Owner: ai_store_user
--

ALTER TABLE public.products_productimage ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.products_productimage_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: products_productvariant; Type: TABLE; Schema: public; Owner: ai_store_user
--

CREATE TABLE public.products_productvariant (
    id bigint NOT NULL,
    size character varying(50),
    sku character varying(100) NOT NULL,
    slug character varying(250) NOT NULL,
    is_active boolean NOT NULL,
    price numeric(10,2) NOT NULL,
    color_id bigint,
    product_id bigint NOT NULL
);


ALTER TABLE public.products_productvariant OWNER TO ai_store_user;

--
-- Name: products_productvariant_id_seq; Type: SEQUENCE; Schema: public; Owner: ai_store_user
--

ALTER TABLE public.products_productvariant ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.products_productvariant_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: products_review; Type: TABLE; Schema: public; Owner: ai_store_user
--

CREATE TABLE public.products_review (
    id bigint NOT NULL,
    rating smallint NOT NULL,
    image character varying(100),
    product_review text NOT NULL,
    slug character varying(250) NOT NULL,
    created_at timestamp with time zone,
    product_id bigint,
    user_id bigint NOT NULL,
    CONSTRAINT products_review_rating_check CHECK ((rating >= 0))
);


ALTER TABLE public.products_review OWNER TO ai_store_user;

--
-- Name: products_review_id_seq; Type: SEQUENCE; Schema: public; Owner: ai_store_user
--

ALTER TABLE public.products_review ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.products_review_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: products_stock; Type: TABLE; Schema: public; Owner: ai_store_user
--

CREATE TABLE public.products_stock (
    id bigint NOT NULL,
    quantity integer NOT NULL,
    reserved_quantity integer NOT NULL,
    slug character varying(250) NOT NULL,
    variant_id bigint NOT NULL,
    CONSTRAINT products_stock_quantity_check CHECK ((quantity >= 0)),
    CONSTRAINT products_stock_reserved_quantity_check CHECK ((reserved_quantity >= 0))
);


ALTER TABLE public.products_stock OWNER TO ai_store_user;

--
-- Name: products_stock_id_seq; Type: SEQUENCE; Schema: public; Owner: ai_store_user
--

ALTER TABLE public.products_stock ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.products_stock_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: accounts_address; Type: TABLE DATA; Schema: public; Owner: ai_store_user
--

COPY public.accounts_address (id, name, phone, pincode, locality, address_line, city, state, landmark, address_type, is_default, latitude, longitude, area, formatted_address, slug, user_id) FROM stdin;
2	sumit	7590951315	160055		Sector 72	Mohali	Punjab		HOME	f	30.7130812	76.7093965	Sector 72	Sector 72, Mohali, S.A.S. Nagar (Mohali) Tahsil, Sahibzada Ajit Singh Nagar, Punjab, 160055, India	sumit-mohali-160055	3
\.


--
-- Data for Name: accounts_customuser; Type: TABLE DATA; Schema: public; Owner: ai_store_user
--

COPY public.accounts_customuser (id, password, last_login, is_superuser, username, first_name, last_name, is_staff, is_active, date_joined, email, is_activated, is_email_verified, otp_created_at, temp_otp) FROM stdin;
2	pbkdf2_sha256$1500000$fbu7Nm1mCZH1o3giTIyMqb$eobKanxUfRcj4kXnirtlaVSEvTyqKV3FmJX3RAo7WJI=	2026-09-16 12:14:59.53852+00	t	admin123			t	t	2026-09-15 10:46:25.022488+00	admin123@gmail.com	t	t	\N	\N
5	pbkdf2_sha256$1500000$oRnDFr6BJG7X26JDWxSCKb$QJhmVTuoji2X6aa1PrqzF95PRR3O7TaOj1JtKh1E28o=	2026-09-16 01:57:02.562961+00	f	vanshsohal	vansh	sohal	f	t	2026-09-15 11:43:59.886708+00	vanshsohal2505@gmail.com	t	t	\N	\N
6	pbkdf2_sha256$1500000$5mLD9zhrFjfQs6ITq65cKV$o0+YNGQiKSmuUiSXvmVBOMHMovHUGn7UNNVxT3S8668=	2026-09-16 12:21:11.949466+00	f	test	test	user	f	t	2026-09-16 12:17:48.942357+00	xzpsdybljmkbensizl@vtmpj.net	t	t	\N	\N
9	pbkdf2_sha256$1500000$xsy8lIW84BnpcTn26asvS2$3hP60p/AELvav2jE4YPtQgKPS0SrgP4vUsXnbtfNC8I=	2026-09-22 13:33:10.146533+00	f	testuser			t	t	2026-09-22 12:42:31.16921+00	wikato5769@art2mart.com	t	t	\N	\N
3	pbkdf2_sha256$1500000$zrK3zr3Y0psq4yGJI1pdOd$QAemX1Hoo5m493QawME7hKpK65j/HIt53bxmBPTn7W8=	2026-09-23 05:30:36.270778+00	f	sumitkumar	sumit	kumar	t	t	2026-09-15 11:19:18.13838+00	sumitsohal963@gmail.com	t	t	\N	\N
8	pbkdf2_sha256$1500000$0x68YwFx7fZrFaWh7fVa8f$kuBJvyCVd4gro87fKwcgO3goz5Spab6ga1BQf4uTpHA=	2026-09-22 11:23:10.974522+00	t	admin1234			t	t	2026-09-22 11:11:26.59592+00	admin1234@gmail.com	f	f	2026-09-24 03:27:54.989563+00	444161
\.


--
-- Data for Name: accounts_customuser_groups; Type: TABLE DATA; Schema: public; Owner: ai_store_user
--

COPY public.accounts_customuser_groups (id, customuser_id, group_id) FROM stdin;
\.


--
-- Data for Name: accounts_customuser_user_permissions; Type: TABLE DATA; Schema: public; Owner: ai_store_user
--

COPY public.accounts_customuser_user_permissions (id, customuser_id, permission_id) FROM stdin;
2	9	64
3	9	82
4	9	84
5	3	84
\.


--
-- Data for Name: accounts_profile; Type: TABLE DATA; Schema: public; Owner: ai_store_user
--

COPY public.accounts_profile (id, phone, profile_picture, slug, name_id) FROM stdin;
2	\N	default/x.jpg	sumitkumar	3
3	\N	default/x.jpg	testuser	9
\.


--
-- Data for Name: accounts_wishlist; Type: TABLE DATA; Schema: public; Owner: ai_store_user
--

COPY public.accounts_wishlist (id, created_at, slug, product_id, user_id) FROM stdin;
\.


--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: ai_store_user
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: ai_store_user
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: ai_store_user
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	3	add_permission
6	Can change permission	3	change_permission
7	Can delete permission	3	delete_permission
8	Can view permission	3	view_permission
9	Can add group	2	add_group
10	Can change group	2	change_group
11	Can delete group	2	delete_group
12	Can view group	2	view_group
13	Can add content type	4	add_contenttype
14	Can change content type	4	change_contenttype
15	Can delete content type	4	delete_contenttype
16	Can view content type	4	view_contenttype
17	Can add session	5	add_session
18	Can change session	5	change_session
19	Can delete session	5	delete_session
20	Can view session	5	view_session
21	Can add Token	6	add_token
22	Can change Token	6	change_token
23	Can delete Token	6	delete_token
24	Can view Token	6	view_token
25	Can add Token	7	add_tokenproxy
26	Can change Token	7	change_tokenproxy
27	Can delete Token	7	delete_tokenproxy
28	Can view Token	7	view_tokenproxy
29	Can add wish list	11	add_wishlist
30	Can change wish list	11	change_wishlist
31	Can delete wish list	11	delete_wishlist
32	Can view wish list	11	view_wishlist
33	Can add user	9	add_customuser
34	Can change user	9	change_customuser
35	Can delete user	9	delete_customuser
36	Can view user	9	view_customuser
37	Can add address	8	add_address
38	Can change address	8	change_address
39	Can delete address	8	delete_address
40	Can view address	8	view_address
41	Can add profile	10	add_profile
42	Can change profile	10	change_profile
43	Can delete profile	10	delete_profile
44	Can view profile	10	view_profile
45	Can add category	12	add_category
46	Can change category	12	change_category
47	Can delete category	12	delete_category
48	Can view category	12	view_category
49	Can add color	13	add_color
50	Can change color	13	change_color
51	Can delete color	13	delete_color
52	Can view color	13	view_color
53	Can add product	14	add_product
54	Can change product	14	change_product
55	Can delete product	14	delete_product
56	Can view product	14	view_product
57	Can add product variant	16	add_productvariant
58	Can change product variant	16	change_productvariant
59	Can delete product variant	16	delete_productvariant
60	Can view product variant	16	view_productvariant
61	Can add review	17	add_review
62	Can change review	17	change_review
63	Can delete review	17	delete_review
64	Can view review	17	view_review
65	Can add stock	18	add_stock
66	Can change stock	18	change_stock
67	Can delete stock	18	delete_stock
68	Can view stock	18	view_stock
69	Can add product image	15	add_productimage
70	Can change product image	15	change_productimage
71	Can delete product image	15	delete_productimage
72	Can view product image	15	view_productimage
73	Can add cart	19	add_cart
74	Can change cart	19	change_cart
75	Can delete cart	19	delete_cart
76	Can view cart	19	view_cart
77	Can add cart item	20	add_cartitem
78	Can change cart item	20	change_cartitem
79	Can delete cart item	20	delete_cartitem
80	Can view cart item	20	view_cartitem
81	Can add order	21	add_order
82	Can change order	21	change_order
83	Can delete order	21	delete_order
84	Can view order	21	view_order
85	Can add order item	22	add_orderitem
86	Can change order item	22	change_orderitem
87	Can delete order item	22	delete_orderitem
88	Can view order item	22	view_orderitem
89	Can add payment	23	add_payment
90	Can change payment	23	change_payment
91	Can delete payment	23	delete_payment
92	Can view payment	23	view_payment
93	Can add Coupon	24	add_coupon
94	Can change Coupon	24	change_coupon
95	Can delete Coupon	24	delete_coupon
96	Can view Coupon	24	view_coupon
97	Can add Coupon Configuration	25	add_couponconfiguration
98	Can change Coupon Configuration	25	change_couponconfiguration
99	Can delete Coupon Configuration	25	delete_couponconfiguration
100	Can view Coupon Configuration	25	view_couponconfiguration
101	Can add Coupon Usage	26	add_couponusage
102	Can change Coupon Usage	26	change_couponusage
103	Can delete Coupon Usage	26	delete_couponusage
104	Can view Coupon Usage	26	view_couponusage
105	Can add conversation	27	add_conversation
106	Can change conversation	27	change_conversation
107	Can delete conversation	27	delete_conversation
108	Can view conversation	27	view_conversation
109	Can add message	28	add_message
110	Can change message	28	change_message
111	Can delete message	28	delete_message
112	Can view message	28	view_message
\.


--
-- Data for Name: authtoken_token; Type: TABLE DATA; Schema: public; Owner: ai_store_user
--

COPY public.authtoken_token (key, created, user_id) FROM stdin;
3ba1d33027e2b443901e7ca0aaf655b906565cbb	2026-09-22 11:14:37.951605+00	8
1500c1b5079ce56aea1571846ac7ee4d16820aca	2026-09-23 05:44:52.427487+00	3
2010029284121eef0ded4c5a6395bc3eee22e3b7	2026-09-23 08:52:57.782847+00	2
\.


--
-- Data for Name: cart_cart; Type: TABLE DATA; Schema: public; Owner: ai_store_user
--

COPY public.cart_cart (id, created_at, slug, user_id) FROM stdin;
2	2026-09-22 07:35:11.084683+00	sumitkumar-cart	3
\.


--
-- Data for Name: cart_cartitem; Type: TABLE DATA; Schema: public; Owner: ai_store_user
--

COPY public.cart_cartitem (id, quantity, slug, cart_id, product_id) FROM stdin;
\.


--
-- Data for Name: chat_conversation; Type: TABLE DATA; Schema: public; Owner: ai_store_user
--

COPY public.chat_conversation (id, status, slug, created_at, updated_at, user_id) FROM stdin;
2	open	ticket-sumitkumar-f25d6eac	2026-09-22 12:00:35.335526+00	2026-09-22 12:00:48.299368+00	3
\.


--
-- Data for Name: chat_message; Type: TABLE DATA; Schema: public; Owner: ai_store_user
--

COPY public.chat_message (id, message, is_read, created_at, conversation_id, sender_id) FROM stdin;
2	Can you help me check my order status?	f	2026-09-22 12:00:48.288641+00	2	3
\.


--
-- Data for Name: coupons_coupon; Type: TABLE DATA; Schema: public; Owner: ai_store_user
--

COPY public.coupons_coupon (id, code, description, discount_type, discount_value, minimum_order_amount, maximum_discount_amount, valid_from, valid_until, usage_limit, used_count, per_user_limit, weekly_user_limit, is_active, slug, created_at, updated_at) FROM stdin;
\.


--
-- Data for Name: coupons_couponconfiguration; Type: TABLE DATA; Schema: public; Owner: ai_store_user
--

COPY public.coupons_couponconfiguration (id, weekly_user_limit, updated_at) FROM stdin;
1	5	2026-09-22 07:35:15.804898+00
\.


--
-- Data for Name: coupons_couponusage; Type: TABLE DATA; Schema: public; Owner: ai_store_user
--

COPY public.coupons_couponusage (id, discount_amount, used_at, slug, coupon_id, order_id, user_id) FROM stdin;
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: ai_store_user
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: ai_store_user
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	group
3	auth	permission
4	contenttypes	contenttype
5	sessions	session
6	authtoken	token
7	authtoken	tokenproxy
8	accounts	address
9	accounts	customuser
10	accounts	profile
11	accounts	wishlist
12	products	category
13	products	color
14	products	product
15	products	productimage
16	products	productvariant
17	products	review
18	products	stock
19	cart	cart
20	cart	cartitem
21	order	order
22	order	orderitem
23	payment	payment
24	coupons	coupon
25	coupons	couponconfiguration
26	coupons	couponusage
27	chat	conversation
28	chat	message
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: ai_store_user
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2026-09-22 07:28:54.934657+00
2	contenttypes	0002_remove_content_type_name	2026-09-22 07:28:54.94773+00
3	auth	0001_initial	2026-09-22 07:28:55.056732+00
4	auth	0002_alter_permission_name_max_length	2026-09-22 07:28:55.064966+00
5	auth	0003_alter_user_email_max_length	2026-09-22 07:28:55.072033+00
6	auth	0004_alter_user_username_opts	2026-09-22 07:28:55.080995+00
7	auth	0005_alter_user_last_login_null	2026-09-22 07:28:55.089158+00
8	auth	0006_require_contenttypes_0002	2026-09-22 07:28:55.09577+00
9	auth	0007_alter_validators_add_error_messages	2026-09-22 07:28:55.104891+00
10	auth	0008_alter_user_username_max_length	2026-09-22 07:28:55.115444+00
11	auth	0009_alter_user_last_name_max_length	2026-09-22 07:28:55.124588+00
12	auth	0010_alter_group_name_max_length	2026-09-22 07:28:55.140111+00
13	auth	0011_update_proxy_permissions	2026-09-22 07:28:55.147457+00
14	auth	0012_alter_user_first_name_max_length	2026-09-22 07:28:55.156617+00
15	accounts	0001_initial	2026-09-22 07:28:55.488788+00
16	products	0001_initial	2026-09-22 07:28:55.81697+00
17	accounts	0002_initial	2026-09-22 07:28:55.888936+00
18	accounts	0003_customuser_is_activated_customuser_is_email_verified_and_more	2026-09-22 07:28:55.932437+00
19	admin	0001_initial	2026-09-22 07:28:55.990322+00
20	admin	0002_logentry_remove_auto_add	2026-09-22 07:28:56.000116+00
21	admin	0003_logentry_add_action_flag_choices	2026-09-22 07:28:56.011148+00
22	authtoken	0001_initial	2026-09-22 07:28:56.058076+00
23	authtoken	0002_auto_20160226_1747	2026-09-22 07:28:56.086523+00
24	authtoken	0003_tokenproxy	2026-09-22 07:28:56.095154+00
25	authtoken	0004_alter_tokenproxy_options	2026-09-22 07:28:56.102653+00
26	cart	0001_initial	2026-09-22 07:28:56.235982+00
27	cart	0002_alter_cart_slug_alter_cartitem_slug	2026-09-22 07:28:56.272194+00
28	chat	0001_initial	2026-09-22 07:28:56.409891+00
29	coupons	0001_initial	2026-09-22 07:28:56.539745+00
30	order	0001_initial	2026-09-22 07:28:56.723607+00
31	coupons	0002_initial	2026-09-22 07:28:56.823538+00
32	order	0002_alter_order_status	2026-09-22 07:28:56.836811+00
33	payment	0001_initial	2026-09-22 07:28:56.965957+00
34	payment	0002_payment_currency_payment_gateway_order_id_and_more	2026-09-22 07:28:57.036368+00
35	products	0002_productimage	2026-09-22 07:28:57.077874+00
36	sessions	0001_initial	2026-09-22 07:28:57.123132+00
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: ai_store_user
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
f1gypxyfbym37myr1dnrgeyza17ugmnw	.eJxVjDsOgzAQRO-ydWQtrI0dyvScAa137UASgcSnQtw9INHQTDHvzWwgPC1Qb_sDWl6Xrl3nNLW9Qg0Ety6yfNNwAv3w8B6NjMMy9dGcirnobJpR0-91ubeDjufuWIdQRFVH4nKRqcpyZMnWoRBGdRgSovUlYRJfYSotefYqPlfPGKjwsP8BJio6sw:1x8v1z:nCUZGDurqUyWk0h6o_yjL5wgEIXLxuNgyAH87UcilgY	2026-10-06 07:35:11.111161+00
gimn0npznmr1k560l4e7mklpyylxx7um	.eJxVjMEOwiAQRP-FsyFbFgp69O43NMsu2KqBpLQn47_bJj3oZQ7z3sxbDbQu47C2NA-TqItCdfrtIvEzlR3Ig8q9aq5lmaeod0UftOlblfS6Hu7fwUht3NYhdFHEIbvcZewzb2nIOmCEKA5CArDeICT2PSRj0ZMX9rk_x4CdV58v3tc3Zw:1x8zAk:zCluJU2sYNm_-Bt1jCD1pp-0VDw-ksIpvt7UCmYkBz8	2026-10-06 12:00:30.325202+00
yrbeypub94q58orcvxhk3ceinnmm8qun	.eJxVjMEOwiAQRP-FsyFbFgp69O43NMsu2KqBpLQn47_bJj3oZQ7z3sxbDbQu47C2NA-TqItCdfrtIvEzlR3Ig8q9aq5lmaeod0UftOlblfS6Hu7fwUht3NYhdFHEIbvcZewzb2nIOmCEKA5CArDeICT2PSRj0ZMX9rk_x4CdV58v3tc3Zw:1x90et:iuDgdiu0P1DvrVDRtHfPLlTnF8GsO-zhVkmiITJE8AE	2026-10-06 13:35:43.082399+00
aa8s46xljetllmk3qzevnlv31hqseemh	eyJjYXJ0Ijp7fX0:1x9bXM:weeg4W8YNvmdyDrI9pZ-MMkR3dHuiCT31g3wqrg4LJA	2026-10-08 04:58:24.882659+00
\.


--
-- Data for Name: order_order; Type: TABLE DATA; Schema: public; Owner: ai_store_user
--

COPY public.order_order (id, order_number, slug, status, total_amount, discount_amount, shipping_name, shipping_phone, shipping_city, shipping_pincode, shipping_address, created_at, updated_at, coupon_id, user_id) FROM stdin;
1	ORD-202609180213-924E34	order-ord-202609180213-924e34	pending_payment	1499.00	0.00	vansh	7590951315	Mohali	160059	1226, RohtakVibe, Sector 60, Mohali, Punjab - 160059	2026-09-22 07:30:21.458758+00	2026-09-22 07:30:21.458758+00	\N	3
2	ORD-202609180241-042B65	order-ord-202609180241-042b65	confirmed	1499.00	0.00	vansh	7590951315	Mohali	160059	1226, RohtakVibe, Sector 60, Mohali, Punjab - 160059	2026-09-22 07:30:21.470663+00	2026-09-22 07:30:21.470663+00	\N	3
3	ORD-202609220736-1C8F80	order-ord-202609220736-1c8f80	pending_payment	4297.00	0.00	sumit	7590951315	Mohali	160055	Sector 72, Mohali, Punjab - 160055	2026-09-22 07:36:38.38359+00	2026-09-22 07:36:38.3836+00	\N	3
4	ORD-202609220737-F68E88	order-ord-202609220737-f68e88	delivered	4297.00	0.00	sumit	7590951315	Mohali	160055	Sector 72, Mohali, Punjab - 160055	2026-09-22 07:37:10.916432+00	2026-09-22 13:26:51.076641+00	\N	3
\.


--
-- Data for Name: order_orderitem; Type: TABLE DATA; Schema: public; Owner: ai_store_user
--

COPY public.order_orderitem (id, quantity, price, slug, order_id, variant_id) FROM stdin;
1	1	1499.00	ord-202609180213-924e34-dark-blue-skinny-jeans-dbsj-28-blu	1	1
2	1	1499.00	ord-202609180241-042b65-dark-blue-skinny-jeans-dbsj-28-blu	2	1
3	2	1499.00	ord-202609220736-1c8f80-dark-blue-skinny-jeans-dbsj-28-blu	3	1
4	1	1299.00	ord-202609220736-1c8f80-classic-slim-fit-jeans-csfj-30-blu	3	4
5	2	1499.00	ord-202609220737-f68e88-dark-blue-skinny-jeans-dbsj-28-blu	4	1
6	1	1299.00	ord-202609220737-f68e88-classic-slim-fit-jeans-csfj-30-blu	4	4
\.


--
-- Data for Name: payment_payment; Type: TABLE DATA; Schema: public; Owner: ai_store_user
--

COPY public.payment_payment (id, payment_method, transaction_id, amount, status, paid_at, created_at, updated_at, slug, order_id, user_id, currency, gateway_order_id, gateway_payment_id, gateway_signature) FROM stdin;
1	online	\N	1499.00	pending	\N	2026-09-22 07:30:21.502558+00	2026-09-22 07:30:21.502558+00	ord-202609180213-924e34-online	1	3	INR	order_TdKYpITt6idgn3	\N	\N
2	online	pay_TdLISHFxirlId5	1499.00	completed	2026-09-18 02:57:06.875189+00	2026-09-22 07:30:21.513623+00	2026-09-22 07:30:21.513623+00	ord-202609180241-042b65-online	2	3	INR	order_TdL3K52oNBIl2D	pay_TdLISHFxirlId5	f27d339a80d8b6737606f17241ad052463aefeb6ebc29e9ffd0360a5985f3345
3	online	\N	4297.00	pending	\N	2026-09-22 07:36:39.341727+00	2026-09-22 07:36:39.341735+00	ord-202609220736-1c8f80-online	3	3	INR	order_Tf0D6iUjvpfIro	\N	\N
4	cod	\N	4297.00	pending	\N	2026-09-22 07:37:10.95854+00	2026-09-22 07:37:10.958546+00	ord-202609220737-f68e88-cod	4	3	INR	\N	\N	\N
\.


--
-- Data for Name: products_category; Type: TABLE DATA; Schema: public; Owner: ai_store_user
--

COPY public.products_category (id, name, slug) FROM stdin;
1	T-Shirts	t-shirts
2	Shirts	shirts
3	Jeans	jeans
4	Shoes	shoes
5	Sneakers	sneakers
6	smartphones	smartphones
\.


--
-- Data for Name: products_color; Type: TABLE DATA; Schema: public; Owner: ai_store_user
--

COPY public.products_color (id, name, hex_code, slug) FROM stdin;
1	Black	#000000	black
2	White	#ffffff	white
3	Blue	#1E3A8A	blue
4	Dark Blue	#17255	dark-blue
\.


--
-- Data for Name: products_product; Type: TABLE DATA; Schema: public; Owner: ai_store_user
--

COPY public.products_product (id, name, slug, image, description, brand, is_active, created_at) FROM stdin;
1	Classic Black T-Shirt	classic-black-t-shirt	product/classic_white.jpg	Premium cotton black T-shirt with a comfortable regular fit, suitable for everyday casual wear.	UrbanStyle	t	2026-09-22 07:30:21.034886+00
2	Premium White Shirt	premium-white-shirt	product/premium_shirt.jpg	Elegant white casual shirt made with lightweight fabric for a clean and comfortable appearance.	Protonic	t	2026-09-22 07:30:21.045005+00
3	AirFlex Running Shoes	airflex-running-shoes	product/airFlexrunning.jpg	Lightweight running shoes designed for daily training, jogging and comfortable long-distance runs.	Nike	t	2026-09-22 07:30:21.051565+00
4	Ultraboost Sport Shoes	ultraboost-sport-shoes	product/ultraboost.jpg	Comfortable sports shoes featuring a cushioned sole for running, workouts and everyday activities.	Adidas	t	2026-09-22 07:30:21.059406+00
5	Classic Slim Fit Jeans	classic-slim-fit-jeans	media/product/jean_1_iyehiw	Classic slim-fit blue jeans made from comfortable stretch denim, suitable for everyday casual wear.	DenimCo	t	2026-09-22 07:30:21.066524+00
6	Dark Blue Skinny Jeans	dark-blue-skinny-jeans	product/dark_blue.jpg	Modern dark-blue skinny jeans featuring a stretchable denim fabric and a comfortable tapered fit.	UrbanDenim	t	2026-09-22 07:30:21.073481+00
8	Apple iPhone 16 Pro	apple-iphone-16-pro	media/product/iphone16_bwl7ed	The Apple iPhone 16 Pro features a titanium design, powerful A18 Pro chip, advanced camera system, and a Super Retina XDR display.	Apple	t	2026-09-22 07:30:21.082114+00
\.


--
-- Data for Name: products_product_cat; Type: TABLE DATA; Schema: public; Owner: ai_store_user
--

COPY public.products_product_cat (id, product_id, category_id) FROM stdin;
1	1	1
2	2	2
3	3	4
4	4	4
5	5	3
6	6	3
7	8	6
\.


--
-- Data for Name: products_productimage; Type: TABLE DATA; Schema: public; Owner: ai_store_user
--

COPY public.products_productimage (id, image, alt_text, created_at, product_id) FROM stdin;
2	media/product/gallery/iphone16_4_xpzlug		2026-09-22 07:30:21.309957+00	8
3	media/product/gallery/iphone16_2_nyejkz		2026-09-22 07:30:21.318183+00	8
4	media/product/gallery/iphone16_5_gashsw		2026-09-22 07:30:21.329208+00	8
5	media/product/gallery/iphone16_3_fchtq3		2026-09-22 07:30:21.335707+00	8
6	media/product/gallery/jean_2_k5w2wx		2026-09-22 07:30:21.345558+00	5
7	media/product/gallery/jean_3_oamexy		2026-09-22 07:30:21.351969+00	5
\.


--
-- Data for Name: products_productvariant; Type: TABLE DATA; Schema: public; Owner: ai_store_user
--

COPY public.products_productvariant (id, size, sku, slug, is_active, price, color_id, product_id) FROM stdin;
1	28	DBSJ-28-BLU	dark-blue-skinny-jeans-dark-blue-28-dbsj-28-blu	t	1499.00	4	6
2	30	DBSJ-30-BLU	dark-blue-skinny-jeans-dark-blue-30-dbsj-30-blu	t	1499.00	4	6
3	34	DBSJ-34-BLU	dark-blue-skinny-jeans-dark-blue-34-dbsj-34-blu	t	1499.00	4	6
4	30	CSFJ-30-BLU	classic-slim-fit-jeans-blue-30-csfj-30-blu	t	1299.00	3	5
5	32	CSFJ-32-BLU	classic-slim-fit-jeans-blue-32-csfj-32-blu	t	1299.00	3	5
6	34	CSFJ-34-BLU	classic-slim-fit-jeans-blue-34-csfj-34-blu	t	1299.00	3	5
7	7	AFRS-7-WHT	airflex-running-shoes-white-7-afrs-7-wht	t	2499.00	2	3
8	8	AFRS-8-WHT	airflex-running-shoes-white-8-afrs-8-wht	t	2499.00	2	3
9	7	AFRS-7-BLK	airflex-running-shoes-black-7-afrs-7-blk	t	1999.00	1	3
10	512GB	APL-IP16P-512-NAT	apple-iphone-16-pro-white-512gb-apl-ip16p-512-nat	t	139900.00	2	8
\.


--
-- Data for Name: products_review; Type: TABLE DATA; Schema: public; Owner: ai_store_user
--

COPY public.products_review (id, rating, image, product_review, slug, created_at, product_id, user_id) FROM stdin;
\.


--
-- Data for Name: products_stock; Type: TABLE DATA; Schema: public; Owner: ai_store_user
--

COPY public.products_stock (id, quantity, reserved_quantity, slug, variant_id) FROM stdin;
2	30	0	stock-dark-blue-skinny-jeans-dark-blue-30-dbsj-30-blu	2
3	35	0	stock-dark-blue-skinny-jeans-dark-blue-34-dbsj-34-blu	3
5	30	0	stock-classic-slim-fit-jeans-blue-32-csfj-32-blu	5
6	40	0	stock-classic-slim-fit-jeans-blue-34-csfj-34-blu	6
7	22	0	stock-airflex-running-shoes-white-7-afrs-7-wht	7
8	20	0	stock-airflex-running-shoes-white-8-afrs-8-wht	8
9	20	0	stock-airflex-running-shoes-black-7-afrs-7-blk	9
10	20	0	stock-apple-iphone-16-pro-white-512gb-apl-ip16p-512-nat	10
1	22	0	stock-dark-blue-skinny-jeans-dark-blue-28-dbsj-28-blu	1
4	34	0	stock-classic-slim-fit-jeans-blue-30-csfj-30-blu	4
\.


--
-- Name: accounts_address_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ai_store_user
--

SELECT pg_catalog.setval('public.accounts_address_id_seq', 2, true);


--
-- Name: accounts_customuser_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ai_store_user
--

SELECT pg_catalog.setval('public.accounts_customuser_groups_id_seq', 1, true);


--
-- Name: accounts_customuser_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ai_store_user
--

SELECT pg_catalog.setval('public.accounts_customuser_id_seq', 9, true);


--
-- Name: accounts_customuser_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ai_store_user
--

SELECT pg_catalog.setval('public.accounts_customuser_user_permissions_id_seq', 5, true);


--
-- Name: accounts_profile_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ai_store_user
--

SELECT pg_catalog.setval('public.accounts_profile_id_seq', 3, true);


--
-- Name: accounts_wishlist_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ai_store_user
--

SELECT pg_catalog.setval('public.accounts_wishlist_id_seq', 1, true);


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ai_store_user
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, true);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ai_store_user
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, true);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ai_store_user
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 112, true);


--
-- Name: cart_cart_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ai_store_user
--

SELECT pg_catalog.setval('public.cart_cart_id_seq', 2, true);


--
-- Name: cart_cartitem_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ai_store_user
--

SELECT pg_catalog.setval('public.cart_cartitem_id_seq', 3, true);


--
-- Name: chat_conversation_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ai_store_user
--

SELECT pg_catalog.setval('public.chat_conversation_id_seq', 2, true);


--
-- Name: chat_message_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ai_store_user
--

SELECT pg_catalog.setval('public.chat_message_id_seq', 2, true);


--
-- Name: coupons_coupon_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ai_store_user
--

SELECT pg_catalog.setval('public.coupons_coupon_id_seq', 1, true);


--
-- Name: coupons_couponconfiguration_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ai_store_user
--

SELECT pg_catalog.setval('public.coupons_couponconfiguration_id_seq', 1, true);


--
-- Name: coupons_couponusage_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ai_store_user
--

SELECT pg_catalog.setval('public.coupons_couponusage_id_seq', 1, true);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ai_store_user
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 1, true);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ai_store_user
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 28, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ai_store_user
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 36, true);


--
-- Name: order_order_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ai_store_user
--

SELECT pg_catalog.setval('public.order_order_id_seq', 4, true);


--
-- Name: order_orderitem_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ai_store_user
--

SELECT pg_catalog.setval('public.order_orderitem_id_seq', 6, true);


--
-- Name: payment_payment_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ai_store_user
--

SELECT pg_catalog.setval('public.payment_payment_id_seq', 4, true);


--
-- Name: products_category_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ai_store_user
--

SELECT pg_catalog.setval('public.products_category_id_seq', 6, true);


--
-- Name: products_color_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ai_store_user
--

SELECT pg_catalog.setval('public.products_color_id_seq', 4, true);


--
-- Name: products_product_cat_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ai_store_user
--

SELECT pg_catalog.setval('public.products_product_cat_id_seq', 7, true);


--
-- Name: products_product_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ai_store_user
--

SELECT pg_catalog.setval('public.products_product_id_seq', 8, true);


--
-- Name: products_productimage_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ai_store_user
--

SELECT pg_catalog.setval('public.products_productimage_id_seq', 7, true);


--
-- Name: products_productvariant_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ai_store_user
--

SELECT pg_catalog.setval('public.products_productvariant_id_seq', 10, true);


--
-- Name: products_review_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ai_store_user
--

SELECT pg_catalog.setval('public.products_review_id_seq', 1, true);


--
-- Name: products_stock_id_seq; Type: SEQUENCE SET; Schema: public; Owner: ai_store_user
--

SELECT pg_catalog.setval('public.products_stock_id_seq', 10, true);


--
-- Name: accounts_address accounts_address_pkey; Type: CONSTRAINT; Schema: public; Owner: ai_store_user
--

ALTER TABLE ONLY public.accounts_address
    ADD CONSTRAINT accounts_address_pkey PRIMARY KEY (id);


--
-- Name: accounts_address accounts_address_slug_key; Type: CONSTRAINT; Schema: public; Owner: ai_store_user
--

ALTER TABLE ONLY public.accounts_address
    ADD CONSTRAINT accounts_address_slug_key UNIQUE (slug);


--
-- Name: accounts_customuser accounts_customuser_email_key; Type: CONSTRAINT; Schema: public; Owner: ai_store_user
--

ALTER TABLE ONLY public.accounts_customuser
    ADD CONSTRAINT accounts_customuser_email_key UNIQUE (email);


--
-- Name: accounts_customuser_groups accounts_customuser_groups_customuser_id_group_id_c074bdcb_uniq; Type: CONSTRAINT; Schema: public; Owner: ai_store_user
--

ALTER TABLE ONLY public.accounts_customuser_groups
    ADD CONSTRAINT accounts_customuser_groups_customuser_id_group_id_c074bdcb_uniq UNIQUE (customuser_id, group_id);


--
-- Name: accounts_customuser_groups accounts_customuser_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: ai_store_user
--

ALTER TABLE ONLY public.accounts_customuser_groups
    ADD CONSTRAINT accounts_customuser_groups_pkey PRIMARY KEY (id);


--
-- Name: accounts_customuser accounts_customuser_pkey; Type: CONSTRAINT; Schema: public; Owner: ai_store_user
--

ALTER TABLE ONLY public.accounts_customuser
    ADD CONSTRAINT accounts_customuser_pkey PRIMARY KEY (id);


--
-- Name: accounts_customuser_user_permissions accounts_customuser_user_customuser_id_permission_9632a709_uniq; Type: CONSTRAINT; Schema: public; Owner: ai_store_user
--

ALTER TABLE ONLY public.accounts_customuser_user_permissions
    ADD CONSTRAINT accounts_customuser_user_customuser_id_permission_9632a709_uniq UNIQUE (customuser_id, permission_id);


--
-- Name: accounts_customuser_user_permissions accounts_customuser_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: ai_store_user
--

ALTER TABLE ONLY public.accounts_customuser_user_permissions
    ADD CONSTRAINT accounts_customuser_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: accounts_customuser accounts_customuser_username_key; Type: CONSTRAINT; Schema: public; Owner: ai_store_user
--

ALTER TABLE ONLY public.accounts_customuser
    ADD CONSTRAINT accounts_customuser_username_key UNIQUE (username);


--
-- Name: accounts_profile accounts_profile_name_id_key; Type: CONSTRAINT; Schema: public; Owner: ai_store_user
--

ALTER TABLE ONLY public.accounts_profile
    ADD CONSTRAINT accounts_profile_name_id_key UNIQUE (name_id);


--
-- Name: accounts_profile accounts_profile_pkey; Type: CONSTRAINT; Schema: public; Owner: ai_store_user
--

ALTER TABLE ONLY public.accounts_profile
    ADD CONSTRAINT accounts_profile_pkey PRIMARY KEY (id);


--
-- Name: accounts_profile accounts_profile_slug_key; Type: CONSTRAINT; Schema: public; Owner: ai_store_user
--

ALTER TABLE ONLY public.accounts_profile
    ADD CONSTRAINT accounts_profile_slug_key UNIQUE (slug);


--
-- Name: accounts_wishlist accounts_wishlist_pkey; Type: CONSTRAINT; Schema: public; Owner: ai_store_user
--

ALTER TABLE ONLY public.accounts_wishlist
    ADD CONSTRAINT accounts_wishlist_pkey PRIMARY KEY (id);


--
-- Name: accounts_wishlist accounts_wishlist_slug_key; Type: CONSTRAINT; Schema: public; Owner: ai_store_user
--

ALTER TABLE ONLY public.accounts_wishlist
    ADD CONSTRAINT accounts_wishlist_slug_key UNIQUE (slug);


--
-- Name: accounts_wishlist accounts_wishlist_user_id_product_id_af323c0a_uniq; Type: CONSTRAINT; Schema: public; Owner: ai_store_user
--

ALTER TABLE ONLY public.accounts_wishlist
    ADD CONSTRAINT accounts_wishlist_user_id_product_id_af323c0a_uniq UNIQUE (user_id, product_id);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: ai_store_user
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: ai_store_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: ai_store_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: ai_store_user
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: ai_store_user
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: ai_store_user
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: authtoken_token authtoken_token_pkey; Type: CONSTRAINT; Schema: public; Owner: ai_store_user
--

ALTER TABLE ONLY public.authtoken_token
    ADD CONSTRAINT authtoken_token_pkey PRIMARY KEY (key);


--
-- Name: authtoken_token authtoken_token_user_id_key; Type: CONSTRAINT; Schema: public; Owner: ai_store_user
--

ALTER TABLE ONLY public.authtoken_token
    ADD CONSTRAINT authtoken_token_user_id_key UNIQUE (user_id);


--
-- Name: cart_cart cart_cart_pkey; Type: CONSTRAINT; Schema: public; Owner: ai_store_user
--

ALTER TABLE ONLY public.cart_cart
    ADD CONSTRAINT cart_cart_pkey PRIMARY KEY (id);


--
-- Name: cart_cart cart_cart_slug_key; Type: CONSTRAINT; Schema: public; Owner: ai_store_user
--

ALTER TABLE ONLY public.cart_cart
    ADD CONSTRAINT cart_cart_slug_key UNIQUE (slug);


--
-- Name: cart_cart cart_cart_user_id_key; Type: CONSTRAINT; Schema: public; Owner: ai_store_user
--

ALTER TABLE ONLY public.cart_cart
    ADD CONSTRAINT cart_cart_user_id_key UNIQUE (user_id);


--
-- Name: cart_cartitem cart_cartitem_pkey; Type: CONSTRAINT; Schema: public; Owner: ai_store_user
--

ALTER TABLE ONLY public.cart_cartitem
    ADD CONSTRAINT cart_cartitem_pkey PRIMARY KEY (id);


--
-- Name: cart_cartitem cart_cartitem_slug_key; Type: CONSTRAINT; Schema: public; Owner: ai_store_user
--

ALTER TABLE ONLY public.cart_cartitem
    ADD CONSTRAINT cart_cartitem_slug_key UNIQUE (slug);


--
-- Name: chat_conversation chat_conversation_pkey; Type: CONSTRAINT; Schema: public; Owner: ai_store_user
--

ALTER TABLE ONLY public.chat_conversation
    ADD CONSTRAINT chat_conversation_pkey PRIMARY KEY (id);


--
-- Name: chat_conversation chat_conversation_slug_key; Type: CONSTRAINT; Schema: public; Owner: ai_store_user
--

ALTER TABLE ONLY public.chat_conversation
    ADD CONSTRAINT chat_conversation_slug_key UNIQUE (slug);


--
-- Name: chat_message chat_message_pkey; Type: CONSTRAINT; Schema: public; Owner: ai_store_user
--

ALTER TABLE ONLY public.chat_message
    ADD CONSTRAINT chat_message_pkey PRIMARY KEY (id);


--
-- Name: coupons_coupon coupons_coupon_code_key; Type: CONSTRAINT; Schema: public; Owner: ai_store_user
--

ALTER TABLE ONLY public.coupons_coupon
    ADD CONSTRAINT coupons_coupon_code_key UNIQUE (code);


--
-- Name: coupons_coupon coupons_coupon_pkey; Type: CONSTRAINT; Schema: public; Owner: ai_store_user
--

ALTER TABLE ONLY public.coupons_coupon
    ADD CONSTRAINT coupons_coupon_pkey PRIMARY KEY (id);


--
-- Name: coupons_coupon coupons_coupon_slug_key; Type: CONSTRAINT; Schema: public; Owner: ai_store_user
--

ALTER TABLE ONLY public.coupons_coupon
    ADD CONSTRAINT coupons_coupon_slug_key UNIQUE (slug);


--
-- Name: coupons_couponconfiguration coupons_couponconfiguration_pkey; Type: CONSTRAINT; Schema: public; Owner: ai_store_user
--

ALTER TABLE ONLY public.coupons_couponconfiguration
    ADD CONSTRAINT coupons_couponconfiguration_pkey PRIMARY KEY (id);


--
-- Name: coupons_couponusage coupons_couponusage_order_id_key; Type: CONSTRAINT; Schema: public; Owner: ai_store_user
--

ALTER TABLE ONLY public.coupons_couponusage
    ADD CONSTRAINT coupons_couponusage_order_id_key UNIQUE (order_id);


--
-- Name: coupons_couponusage coupons_couponusage_pkey; Type: CONSTRAINT; Schema: public; Owner: ai_store_user
--

ALTER TABLE ONLY public.coupons_couponusage
    ADD CONSTRAINT coupons_couponusage_pkey PRIMARY KEY (id);


--
-- Name: coupons_couponusage coupons_couponusage_slug_key; Type: CONSTRAINT; Schema: public; Owner: ai_store_user
--

ALTER TABLE ONLY public.coupons_couponusage
    ADD CONSTRAINT coupons_couponusage_slug_key UNIQUE (slug);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: ai_store_user
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: ai_store_user
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: ai_store_user
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: ai_store_user
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: ai_store_user
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: order_order order_order_order_number_key; Type: CONSTRAINT; Schema: public; Owner: ai_store_user
--

ALTER TABLE ONLY public.order_order
    ADD CONSTRAINT order_order_order_number_key UNIQUE (order_number);


--
-- Name: order_order order_order_pkey; Type: CONSTRAINT; Schema: public; Owner: ai_store_user
--

ALTER TABLE ONLY public.order_order
    ADD CONSTRAINT order_order_pkey PRIMARY KEY (id);


--
-- Name: order_order order_order_slug_key; Type: CONSTRAINT; Schema: public; Owner: ai_store_user
--

ALTER TABLE ONLY public.order_order
    ADD CONSTRAINT order_order_slug_key UNIQUE (slug);


--
-- Name: order_orderitem order_orderitem_pkey; Type: CONSTRAINT; Schema: public; Owner: ai_store_user
--

ALTER TABLE ONLY public.order_orderitem
    ADD CONSTRAINT order_orderitem_pkey PRIMARY KEY (id);


--
-- Name: order_orderitem order_orderitem_slug_key; Type: CONSTRAINT; Schema: public; Owner: ai_store_user
--

ALTER TABLE ONLY public.order_orderitem
    ADD CONSTRAINT order_orderitem_slug_key UNIQUE (slug);


--
-- Name: payment_payment payment_payment_order_id_key; Type: CONSTRAINT; Schema: public; Owner: ai_store_user
--

ALTER TABLE ONLY public.payment_payment
    ADD CONSTRAINT payment_payment_order_id_key UNIQUE (order_id);


--
-- Name: payment_payment payment_payment_pkey; Type: CONSTRAINT; Schema: public; Owner: ai_store_user
--

ALTER TABLE ONLY public.payment_payment
    ADD CONSTRAINT payment_payment_pkey PRIMARY KEY (id);


--
-- Name: payment_payment payment_payment_slug_key; Type: CONSTRAINT; Schema: public; Owner: ai_store_user
--

ALTER TABLE ONLY public.payment_payment
    ADD CONSTRAINT payment_payment_slug_key UNIQUE (slug);


--
-- Name: payment_payment payment_payment_transaction_id_key; Type: CONSTRAINT; Schema: public; Owner: ai_store_user
--

ALTER TABLE ONLY public.payment_payment
    ADD CONSTRAINT payment_payment_transaction_id_key UNIQUE (transaction_id);


--
-- Name: products_category products_category_pkey; Type: CONSTRAINT; Schema: public; Owner: ai_store_user
--

ALTER TABLE ONLY public.products_category
    ADD CONSTRAINT products_category_pkey PRIMARY KEY (id);


--
-- Name: products_category products_category_slug_key; Type: CONSTRAINT; Schema: public; Owner: ai_store_user
--

ALTER TABLE ONLY public.products_category
    ADD CONSTRAINT products_category_slug_key UNIQUE (slug);


--
-- Name: products_color products_color_pkey; Type: CONSTRAINT; Schema: public; Owner: ai_store_user
--

ALTER TABLE ONLY public.products_color
    ADD CONSTRAINT products_color_pkey PRIMARY KEY (id);


--
-- Name: products_color products_color_slug_key; Type: CONSTRAINT; Schema: public; Owner: ai_store_user
--

ALTER TABLE ONLY public.products_color
    ADD CONSTRAINT products_color_slug_key UNIQUE (slug);


--
-- Name: products_product_cat products_product_cat_pkey; Type: CONSTRAINT; Schema: public; Owner: ai_store_user
--

ALTER TABLE ONLY public.products_product_cat
    ADD CONSTRAINT products_product_cat_pkey PRIMARY KEY (id);


--
-- Name: products_product_cat products_product_cat_product_id_category_id_c4b0a302_uniq; Type: CONSTRAINT; Schema: public; Owner: ai_store_user
--

ALTER TABLE ONLY public.products_product_cat
    ADD CONSTRAINT products_product_cat_product_id_category_id_c4b0a302_uniq UNIQUE (product_id, category_id);


--
-- Name: products_product products_product_pkey; Type: CONSTRAINT; Schema: public; Owner: ai_store_user
--

ALTER TABLE ONLY public.products_product
    ADD CONSTRAINT products_product_pkey PRIMARY KEY (id);


--
-- Name: products_product products_product_slug_key; Type: CONSTRAINT; Schema: public; Owner: ai_store_user
--

ALTER TABLE ONLY public.products_product
    ADD CONSTRAINT products_product_slug_key UNIQUE (slug);


--
-- Name: products_productimage products_productimage_pkey; Type: CONSTRAINT; Schema: public; Owner: ai_store_user
--

ALTER TABLE ONLY public.products_productimage
    ADD CONSTRAINT products_productimage_pkey PRIMARY KEY (id);


--
-- Name: products_productvariant products_productvariant_pkey; Type: CONSTRAINT; Schema: public; Owner: ai_store_user
--

ALTER TABLE ONLY public.products_productvariant
    ADD CONSTRAINT products_productvariant_pkey PRIMARY KEY (id);


--
-- Name: products_productvariant products_productvariant_sku_key; Type: CONSTRAINT; Schema: public; Owner: ai_store_user
--

ALTER TABLE ONLY public.products_productvariant
    ADD CONSTRAINT products_productvariant_sku_key UNIQUE (sku);


--
-- Name: products_productvariant products_productvariant_slug_key; Type: CONSTRAINT; Schema: public; Owner: ai_store_user
--

ALTER TABLE ONLY public.products_productvariant
    ADD CONSTRAINT products_productvariant_slug_key UNIQUE (slug);


--
-- Name: products_review products_review_pkey; Type: CONSTRAINT; Schema: public; Owner: ai_store_user
--

ALTER TABLE ONLY public.products_review
    ADD CONSTRAINT products_review_pkey PRIMARY KEY (id);


--
-- Name: products_review products_review_slug_key; Type: CONSTRAINT; Schema: public; Owner: ai_store_user
--

ALTER TABLE ONLY public.products_review
    ADD CONSTRAINT products_review_slug_key UNIQUE (slug);


--
-- Name: products_stock products_stock_pkey; Type: CONSTRAINT; Schema: public; Owner: ai_store_user
--

ALTER TABLE ONLY public.products_stock
    ADD CONSTRAINT products_stock_pkey PRIMARY KEY (id);


--
-- Name: products_stock products_stock_slug_key; Type: CONSTRAINT; Schema: public; Owner: ai_store_user
--

ALTER TABLE ONLY public.products_stock
    ADD CONSTRAINT products_stock_slug_key UNIQUE (slug);


--
-- Name: products_stock products_stock_variant_id_key; Type: CONSTRAINT; Schema: public; Owner: ai_store_user
--

ALTER TABLE ONLY public.products_stock
    ADD CONSTRAINT products_stock_variant_id_key UNIQUE (variant_id);


--
-- Name: accounts_address_slug_701b9f58_like; Type: INDEX; Schema: public; Owner: ai_store_user
--

CREATE INDEX accounts_address_slug_701b9f58_like ON public.accounts_address USING btree (slug varchar_pattern_ops);


--
-- Name: accounts_address_user_id_c8c74ddf; Type: INDEX; Schema: public; Owner: ai_store_user
--

CREATE INDEX accounts_address_user_id_c8c74ddf ON public.accounts_address USING btree (user_id);


--
-- Name: accounts_customuser_email_4fd8e7ce_like; Type: INDEX; Schema: public; Owner: ai_store_user
--

CREATE INDEX accounts_customuser_email_4fd8e7ce_like ON public.accounts_customuser USING btree (email varchar_pattern_ops);


--
-- Name: accounts_customuser_groups_customuser_id_bc55088e; Type: INDEX; Schema: public; Owner: ai_store_user
--

CREATE INDEX accounts_customuser_groups_customuser_id_bc55088e ON public.accounts_customuser_groups USING btree (customuser_id);


--
-- Name: accounts_customuser_groups_group_id_86ba5f9e; Type: INDEX; Schema: public; Owner: ai_store_user
--

CREATE INDEX accounts_customuser_groups_group_id_86ba5f9e ON public.accounts_customuser_groups USING btree (group_id);


--
-- Name: accounts_customuser_user_permissions_customuser_id_0deaefae; Type: INDEX; Schema: public; Owner: ai_store_user
--

CREATE INDEX accounts_customuser_user_permissions_customuser_id_0deaefae ON public.accounts_customuser_user_permissions USING btree (customuser_id);


--
-- Name: accounts_customuser_user_permissions_permission_id_aea3d0e5; Type: INDEX; Schema: public; Owner: ai_store_user
--

CREATE INDEX accounts_customuser_user_permissions_permission_id_aea3d0e5 ON public.accounts_customuser_user_permissions USING btree (permission_id);


--
-- Name: accounts_customuser_username_722f3555_like; Type: INDEX; Schema: public; Owner: ai_store_user
--

CREATE INDEX accounts_customuser_username_722f3555_like ON public.accounts_customuser USING btree (username varchar_pattern_ops);


--
-- Name: accounts_profile_slug_8a7a322e_like; Type: INDEX; Schema: public; Owner: ai_store_user
--

CREATE INDEX accounts_profile_slug_8a7a322e_like ON public.accounts_profile USING btree (slug varchar_pattern_ops);


--
-- Name: accounts_wishlist_product_id_40d7fd21; Type: INDEX; Schema: public; Owner: ai_store_user
--

CREATE INDEX accounts_wishlist_product_id_40d7fd21 ON public.accounts_wishlist USING btree (product_id);


--
-- Name: accounts_wishlist_slug_a5fe6c0d_like; Type: INDEX; Schema: public; Owner: ai_store_user
--

CREATE INDEX accounts_wishlist_slug_a5fe6c0d_like ON public.accounts_wishlist USING btree (slug varchar_pattern_ops);


--
-- Name: accounts_wishlist_user_id_9f03cf05; Type: INDEX; Schema: public; Owner: ai_store_user
--

CREATE INDEX accounts_wishlist_user_id_9f03cf05 ON public.accounts_wishlist USING btree (user_id);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: ai_store_user
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: ai_store_user
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: ai_store_user
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: ai_store_user
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: authtoken_token_key_10f0b77e_like; Type: INDEX; Schema: public; Owner: ai_store_user
--

CREATE INDEX authtoken_token_key_10f0b77e_like ON public.authtoken_token USING btree (key varchar_pattern_ops);


--
-- Name: cart_cart_slug_a70a5fa2_like; Type: INDEX; Schema: public; Owner: ai_store_user
--

CREATE INDEX cart_cart_slug_a70a5fa2_like ON public.cart_cart USING btree (slug varchar_pattern_ops);


--
-- Name: cart_cartitem_cart_id_370ad265; Type: INDEX; Schema: public; Owner: ai_store_user
--

CREATE INDEX cart_cartitem_cart_id_370ad265 ON public.cart_cartitem USING btree (cart_id);


--
-- Name: cart_cartitem_product_id_b24e265a; Type: INDEX; Schema: public; Owner: ai_store_user
--

CREATE INDEX cart_cartitem_product_id_b24e265a ON public.cart_cartitem USING btree (product_id);


--
-- Name: cart_cartitem_slug_dfc6f974_like; Type: INDEX; Schema: public; Owner: ai_store_user
--

CREATE INDEX cart_cartitem_slug_dfc6f974_like ON public.cart_cartitem USING btree (slug varchar_pattern_ops);


--
-- Name: chat_conversation_slug_06c1ad5b_like; Type: INDEX; Schema: public; Owner: ai_store_user
--

CREATE INDEX chat_conversation_slug_06c1ad5b_like ON public.chat_conversation USING btree (slug varchar_pattern_ops);


--
-- Name: chat_conversation_user_id_15357b84; Type: INDEX; Schema: public; Owner: ai_store_user
--

CREATE INDEX chat_conversation_user_id_15357b84 ON public.chat_conversation USING btree (user_id);


--
-- Name: chat_message_conversation_id_a1207bf4; Type: INDEX; Schema: public; Owner: ai_store_user
--

CREATE INDEX chat_message_conversation_id_a1207bf4 ON public.chat_message USING btree (conversation_id);


--
-- Name: chat_message_sender_id_991c686c; Type: INDEX; Schema: public; Owner: ai_store_user
--

CREATE INDEX chat_message_sender_id_991c686c ON public.chat_message USING btree (sender_id);


--
-- Name: coupons_coupon_code_40174643_like; Type: INDEX; Schema: public; Owner: ai_store_user
--

CREATE INDEX coupons_coupon_code_40174643_like ON public.coupons_coupon USING btree (code varchar_pattern_ops);


--
-- Name: coupons_coupon_slug_d8178373_like; Type: INDEX; Schema: public; Owner: ai_store_user
--

CREATE INDEX coupons_coupon_slug_d8178373_like ON public.coupons_coupon USING btree (slug varchar_pattern_ops);


--
-- Name: coupons_couponusage_coupon_id_b648d42e; Type: INDEX; Schema: public; Owner: ai_store_user
--

CREATE INDEX coupons_couponusage_coupon_id_b648d42e ON public.coupons_couponusage USING btree (coupon_id);


--
-- Name: coupons_couponusage_slug_3f80f2ee_like; Type: INDEX; Schema: public; Owner: ai_store_user
--

CREATE INDEX coupons_couponusage_slug_3f80f2ee_like ON public.coupons_couponusage USING btree (slug varchar_pattern_ops);


--
-- Name: coupons_couponusage_used_at_0382896c; Type: INDEX; Schema: public; Owner: ai_store_user
--

CREATE INDEX coupons_couponusage_used_at_0382896c ON public.coupons_couponusage USING btree (used_at);


--
-- Name: coupons_couponusage_user_id_687967d8; Type: INDEX; Schema: public; Owner: ai_store_user
--

CREATE INDEX coupons_couponusage_user_id_687967d8 ON public.coupons_couponusage USING btree (user_id);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: ai_store_user
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: ai_store_user
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: ai_store_user
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: ai_store_user
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: idx_coupon_user; Type: INDEX; Schema: public; Owner: ai_store_user
--

CREATE INDEX idx_coupon_user ON public.coupons_couponusage USING btree (coupon_id, user_id);


--
-- Name: idx_user_used_at; Type: INDEX; Schema: public; Owner: ai_store_user
--

CREATE INDEX idx_user_used_at ON public.coupons_couponusage USING btree (user_id, used_at);


--
-- Name: order_order_coupon_id_dc594905; Type: INDEX; Schema: public; Owner: ai_store_user
--

CREATE INDEX order_order_coupon_id_dc594905 ON public.order_order USING btree (coupon_id);


--
-- Name: order_order_order_number_21369dec_like; Type: INDEX; Schema: public; Owner: ai_store_user
--

CREATE INDEX order_order_order_number_21369dec_like ON public.order_order USING btree (order_number varchar_pattern_ops);


--
-- Name: order_order_slug_b3514f70_like; Type: INDEX; Schema: public; Owner: ai_store_user
--

CREATE INDEX order_order_slug_b3514f70_like ON public.order_order USING btree (slug varchar_pattern_ops);


--
-- Name: order_order_user_id_7cf9bc2b; Type: INDEX; Schema: public; Owner: ai_store_user
--

CREATE INDEX order_order_user_id_7cf9bc2b ON public.order_order USING btree (user_id);


--
-- Name: order_orderitem_order_id_aba34f44; Type: INDEX; Schema: public; Owner: ai_store_user
--

CREATE INDEX order_orderitem_order_id_aba34f44 ON public.order_orderitem USING btree (order_id);


--
-- Name: order_orderitem_slug_e56c76ff_like; Type: INDEX; Schema: public; Owner: ai_store_user
--

CREATE INDEX order_orderitem_slug_e56c76ff_like ON public.order_orderitem USING btree (slug varchar_pattern_ops);


--
-- Name: order_orderitem_variant_id_8e6b11d0; Type: INDEX; Schema: public; Owner: ai_store_user
--

CREATE INDEX order_orderitem_variant_id_8e6b11d0 ON public.order_orderitem USING btree (variant_id);


--
-- Name: payment_payment_slug_8681915b_like; Type: INDEX; Schema: public; Owner: ai_store_user
--

CREATE INDEX payment_payment_slug_8681915b_like ON public.payment_payment USING btree (slug varchar_pattern_ops);


--
-- Name: payment_payment_transaction_id_527e9f51_like; Type: INDEX; Schema: public; Owner: ai_store_user
--

CREATE INDEX payment_payment_transaction_id_527e9f51_like ON public.payment_payment USING btree (transaction_id varchar_pattern_ops);


--
-- Name: payment_payment_user_id_f428ca02; Type: INDEX; Schema: public; Owner: ai_store_user
--

CREATE INDEX payment_payment_user_id_f428ca02 ON public.payment_payment USING btree (user_id);


--
-- Name: products_category_slug_c558efae_like; Type: INDEX; Schema: public; Owner: ai_store_user
--

CREATE INDEX products_category_slug_c558efae_like ON public.products_category USING btree (slug varchar_pattern_ops);


--
-- Name: products_color_slug_ff7c93c4_like; Type: INDEX; Schema: public; Owner: ai_store_user
--

CREATE INDEX products_color_slug_ff7c93c4_like ON public.products_color USING btree (slug varchar_pattern_ops);


--
-- Name: products_product_cat_category_id_dfe2fbee; Type: INDEX; Schema: public; Owner: ai_store_user
--

CREATE INDEX products_product_cat_category_id_dfe2fbee ON public.products_product_cat USING btree (category_id);


--
-- Name: products_product_cat_product_id_23f7f3b1; Type: INDEX; Schema: public; Owner: ai_store_user
--

CREATE INDEX products_product_cat_product_id_23f7f3b1 ON public.products_product_cat USING btree (product_id);


--
-- Name: products_product_slug_70d3148d_like; Type: INDEX; Schema: public; Owner: ai_store_user
--

CREATE INDEX products_product_slug_70d3148d_like ON public.products_product USING btree (slug varchar_pattern_ops);


--
-- Name: products_productimage_product_id_e747596a; Type: INDEX; Schema: public; Owner: ai_store_user
--

CREATE INDEX products_productimage_product_id_e747596a ON public.products_productimage USING btree (product_id);


--
-- Name: products_productvariant_color_id_c213fea2; Type: INDEX; Schema: public; Owner: ai_store_user
--

CREATE INDEX products_productvariant_color_id_c213fea2 ON public.products_productvariant USING btree (color_id);


--
-- Name: products_productvariant_product_id_d9c22902; Type: INDEX; Schema: public; Owner: ai_store_user
--

CREATE INDEX products_productvariant_product_id_d9c22902 ON public.products_productvariant USING btree (product_id);


--
-- Name: products_productvariant_sku_1b692018_like; Type: INDEX; Schema: public; Owner: ai_store_user
--

CREATE INDEX products_productvariant_sku_1b692018_like ON public.products_productvariant USING btree (sku varchar_pattern_ops);


--
-- Name: products_productvariant_slug_6b030df8_like; Type: INDEX; Schema: public; Owner: ai_store_user
--

CREATE INDEX products_productvariant_slug_6b030df8_like ON public.products_productvariant USING btree (slug varchar_pattern_ops);


--
-- Name: products_review_product_id_d933ffa7; Type: INDEX; Schema: public; Owner: ai_store_user
--

CREATE INDEX products_review_product_id_d933ffa7 ON public.products_review USING btree (product_id);


--
-- Name: products_review_slug_ddd25a54_like; Type: INDEX; Schema: public; Owner: ai_store_user
--

CREATE INDEX products_review_slug_ddd25a54_like ON public.products_review USING btree (slug varchar_pattern_ops);


--
-- Name: products_review_user_id_2e53b831; Type: INDEX; Schema: public; Owner: ai_store_user
--

CREATE INDEX products_review_user_id_2e53b831 ON public.products_review USING btree (user_id);


--
-- Name: products_stock_slug_c07fb97c_like; Type: INDEX; Schema: public; Owner: ai_store_user
--

CREATE INDEX products_stock_slug_c07fb97c_like ON public.products_stock USING btree (slug varchar_pattern_ops);


--
-- Name: accounts_address accounts_address_user_id_c8c74ddf_fk_accounts_customuser_id; Type: FK CONSTRAINT; Schema: public; Owner: ai_store_user
--

ALTER TABLE ONLY public.accounts_address
    ADD CONSTRAINT accounts_address_user_id_c8c74ddf_fk_accounts_customuser_id FOREIGN KEY (user_id) REFERENCES public.accounts_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: accounts_customuser_user_permissions accounts_customuser__customuser_id_0deaefae_fk_accounts_; Type: FK CONSTRAINT; Schema: public; Owner: ai_store_user
--

ALTER TABLE ONLY public.accounts_customuser_user_permissions
    ADD CONSTRAINT accounts_customuser__customuser_id_0deaefae_fk_accounts_ FOREIGN KEY (customuser_id) REFERENCES public.accounts_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: accounts_customuser_groups accounts_customuser__customuser_id_bc55088e_fk_accounts_; Type: FK CONSTRAINT; Schema: public; Owner: ai_store_user
--

ALTER TABLE ONLY public.accounts_customuser_groups
    ADD CONSTRAINT accounts_customuser__customuser_id_bc55088e_fk_accounts_ FOREIGN KEY (customuser_id) REFERENCES public.accounts_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: accounts_customuser_user_permissions accounts_customuser__permission_id_aea3d0e5_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: ai_store_user
--

ALTER TABLE ONLY public.accounts_customuser_user_permissions
    ADD CONSTRAINT accounts_customuser__permission_id_aea3d0e5_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: accounts_customuser_groups accounts_customuser_groups_group_id_86ba5f9e_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: ai_store_user
--

ALTER TABLE ONLY public.accounts_customuser_groups
    ADD CONSTRAINT accounts_customuser_groups_group_id_86ba5f9e_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: accounts_profile accounts_profile_name_id_3bf33b3f_fk_accounts_customuser_id; Type: FK CONSTRAINT; Schema: public; Owner: ai_store_user
--

ALTER TABLE ONLY public.accounts_profile
    ADD CONSTRAINT accounts_profile_name_id_3bf33b3f_fk_accounts_customuser_id FOREIGN KEY (name_id) REFERENCES public.accounts_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: accounts_wishlist accounts_wishlist_product_id_40d7fd21_fk_products_product_id; Type: FK CONSTRAINT; Schema: public; Owner: ai_store_user
--

ALTER TABLE ONLY public.accounts_wishlist
    ADD CONSTRAINT accounts_wishlist_product_id_40d7fd21_fk_products_product_id FOREIGN KEY (product_id) REFERENCES public.products_product(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: accounts_wishlist accounts_wishlist_user_id_9f03cf05_fk_accounts_customuser_id; Type: FK CONSTRAINT; Schema: public; Owner: ai_store_user
--

ALTER TABLE ONLY public.accounts_wishlist
    ADD CONSTRAINT accounts_wishlist_user_id_9f03cf05_fk_accounts_customuser_id FOREIGN KEY (user_id) REFERENCES public.accounts_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: ai_store_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: ai_store_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: ai_store_user
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: authtoken_token authtoken_token_user_id_35299eff_fk_accounts_customuser_id; Type: FK CONSTRAINT; Schema: public; Owner: ai_store_user
--

ALTER TABLE ONLY public.authtoken_token
    ADD CONSTRAINT authtoken_token_user_id_35299eff_fk_accounts_customuser_id FOREIGN KEY (user_id) REFERENCES public.accounts_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: cart_cart cart_cart_user_id_9b4220b9_fk_accounts_customuser_id; Type: FK CONSTRAINT; Schema: public; Owner: ai_store_user
--

ALTER TABLE ONLY public.cart_cart
    ADD CONSTRAINT cart_cart_user_id_9b4220b9_fk_accounts_customuser_id FOREIGN KEY (user_id) REFERENCES public.accounts_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: cart_cartitem cart_cartitem_cart_id_370ad265_fk_cart_cart_id; Type: FK CONSTRAINT; Schema: public; Owner: ai_store_user
--

ALTER TABLE ONLY public.cart_cartitem
    ADD CONSTRAINT cart_cartitem_cart_id_370ad265_fk_cart_cart_id FOREIGN KEY (cart_id) REFERENCES public.cart_cart(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: cart_cartitem cart_cartitem_product_id_b24e265a_fk_products_productvariant_id; Type: FK CONSTRAINT; Schema: public; Owner: ai_store_user
--

ALTER TABLE ONLY public.cart_cartitem
    ADD CONSTRAINT cart_cartitem_product_id_b24e265a_fk_products_productvariant_id FOREIGN KEY (product_id) REFERENCES public.products_productvariant(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: chat_conversation chat_conversation_user_id_15357b84_fk_accounts_customuser_id; Type: FK CONSTRAINT; Schema: public; Owner: ai_store_user
--

ALTER TABLE ONLY public.chat_conversation
    ADD CONSTRAINT chat_conversation_user_id_15357b84_fk_accounts_customuser_id FOREIGN KEY (user_id) REFERENCES public.accounts_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: chat_message chat_message_conversation_id_a1207bf4_fk_chat_conversation_id; Type: FK CONSTRAINT; Schema: public; Owner: ai_store_user
--

ALTER TABLE ONLY public.chat_message
    ADD CONSTRAINT chat_message_conversation_id_a1207bf4_fk_chat_conversation_id FOREIGN KEY (conversation_id) REFERENCES public.chat_conversation(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: chat_message chat_message_sender_id_991c686c_fk_accounts_customuser_id; Type: FK CONSTRAINT; Schema: public; Owner: ai_store_user
--

ALTER TABLE ONLY public.chat_message
    ADD CONSTRAINT chat_message_sender_id_991c686c_fk_accounts_customuser_id FOREIGN KEY (sender_id) REFERENCES public.accounts_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: coupons_couponusage coupons_couponusage_coupon_id_b648d42e_fk_coupons_coupon_id; Type: FK CONSTRAINT; Schema: public; Owner: ai_store_user
--

ALTER TABLE ONLY public.coupons_couponusage
    ADD CONSTRAINT coupons_couponusage_coupon_id_b648d42e_fk_coupons_coupon_id FOREIGN KEY (coupon_id) REFERENCES public.coupons_coupon(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: coupons_couponusage coupons_couponusage_order_id_9eb51d6d_fk_order_order_id; Type: FK CONSTRAINT; Schema: public; Owner: ai_store_user
--

ALTER TABLE ONLY public.coupons_couponusage
    ADD CONSTRAINT coupons_couponusage_order_id_9eb51d6d_fk_order_order_id FOREIGN KEY (order_id) REFERENCES public.order_order(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: coupons_couponusage coupons_couponusage_user_id_687967d8_fk_accounts_customuser_id; Type: FK CONSTRAINT; Schema: public; Owner: ai_store_user
--

ALTER TABLE ONLY public.coupons_couponusage
    ADD CONSTRAINT coupons_couponusage_user_id_687967d8_fk_accounts_customuser_id FOREIGN KEY (user_id) REFERENCES public.accounts_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: ai_store_user
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_accounts_customuser_id; Type: FK CONSTRAINT; Schema: public; Owner: ai_store_user
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_accounts_customuser_id FOREIGN KEY (user_id) REFERENCES public.accounts_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: order_order order_order_coupon_id_dc594905_fk_coupons_coupon_id; Type: FK CONSTRAINT; Schema: public; Owner: ai_store_user
--

ALTER TABLE ONLY public.order_order
    ADD CONSTRAINT order_order_coupon_id_dc594905_fk_coupons_coupon_id FOREIGN KEY (coupon_id) REFERENCES public.coupons_coupon(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: order_order order_order_user_id_7cf9bc2b_fk_accounts_customuser_id; Type: FK CONSTRAINT; Schema: public; Owner: ai_store_user
--

ALTER TABLE ONLY public.order_order
    ADD CONSTRAINT order_order_user_id_7cf9bc2b_fk_accounts_customuser_id FOREIGN KEY (user_id) REFERENCES public.accounts_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: order_orderitem order_orderitem_order_id_aba34f44_fk_order_order_id; Type: FK CONSTRAINT; Schema: public; Owner: ai_store_user
--

ALTER TABLE ONLY public.order_orderitem
    ADD CONSTRAINT order_orderitem_order_id_aba34f44_fk_order_order_id FOREIGN KEY (order_id) REFERENCES public.order_order(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: order_orderitem order_orderitem_variant_id_8e6b11d0_fk_products_; Type: FK CONSTRAINT; Schema: public; Owner: ai_store_user
--

ALTER TABLE ONLY public.order_orderitem
    ADD CONSTRAINT order_orderitem_variant_id_8e6b11d0_fk_products_ FOREIGN KEY (variant_id) REFERENCES public.products_productvariant(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: payment_payment payment_payment_order_id_22b45881_fk_order_order_id; Type: FK CONSTRAINT; Schema: public; Owner: ai_store_user
--

ALTER TABLE ONLY public.payment_payment
    ADD CONSTRAINT payment_payment_order_id_22b45881_fk_order_order_id FOREIGN KEY (order_id) REFERENCES public.order_order(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: payment_payment payment_payment_user_id_f428ca02_fk_accounts_customuser_id; Type: FK CONSTRAINT; Schema: public; Owner: ai_store_user
--

ALTER TABLE ONLY public.payment_payment
    ADD CONSTRAINT payment_payment_user_id_f428ca02_fk_accounts_customuser_id FOREIGN KEY (user_id) REFERENCES public.accounts_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: products_product_cat products_product_cat_category_id_dfe2fbee_fk_products_; Type: FK CONSTRAINT; Schema: public; Owner: ai_store_user
--

ALTER TABLE ONLY public.products_product_cat
    ADD CONSTRAINT products_product_cat_category_id_dfe2fbee_fk_products_ FOREIGN KEY (category_id) REFERENCES public.products_category(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: products_product_cat products_product_cat_product_id_23f7f3b1_fk_products_product_id; Type: FK CONSTRAINT; Schema: public; Owner: ai_store_user
--

ALTER TABLE ONLY public.products_product_cat
    ADD CONSTRAINT products_product_cat_product_id_23f7f3b1_fk_products_product_id FOREIGN KEY (product_id) REFERENCES public.products_product(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: products_productimage products_productimag_product_id_e747596a_fk_products_; Type: FK CONSTRAINT; Schema: public; Owner: ai_store_user
--

ALTER TABLE ONLY public.products_productimage
    ADD CONSTRAINT products_productimag_product_id_e747596a_fk_products_ FOREIGN KEY (product_id) REFERENCES public.products_product(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: products_productvariant products_productvari_product_id_d9c22902_fk_products_; Type: FK CONSTRAINT; Schema: public; Owner: ai_store_user
--

ALTER TABLE ONLY public.products_productvariant
    ADD CONSTRAINT products_productvari_product_id_d9c22902_fk_products_ FOREIGN KEY (product_id) REFERENCES public.products_product(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: products_productvariant products_productvariant_color_id_c213fea2_fk_products_color_id; Type: FK CONSTRAINT; Schema: public; Owner: ai_store_user
--

ALTER TABLE ONLY public.products_productvariant
    ADD CONSTRAINT products_productvariant_color_id_c213fea2_fk_products_color_id FOREIGN KEY (color_id) REFERENCES public.products_color(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: products_review products_review_product_id_d933ffa7_fk_products_product_id; Type: FK CONSTRAINT; Schema: public; Owner: ai_store_user
--

ALTER TABLE ONLY public.products_review
    ADD CONSTRAINT products_review_product_id_d933ffa7_fk_products_product_id FOREIGN KEY (product_id) REFERENCES public.products_product(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: products_review products_review_user_id_2e53b831_fk_accounts_customuser_id; Type: FK CONSTRAINT; Schema: public; Owner: ai_store_user
--

ALTER TABLE ONLY public.products_review
    ADD CONSTRAINT products_review_user_id_2e53b831_fk_accounts_customuser_id FOREIGN KEY (user_id) REFERENCES public.accounts_customuser(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: products_stock products_stock_variant_id_dc51ed5d_fk_products_; Type: FK CONSTRAINT; Schema: public; Owner: ai_store_user
--

ALTER TABLE ONLY public.products_stock
    ADD CONSTRAINT products_stock_variant_id_dc51ed5d_fk_products_ FOREIGN KEY (variant_id) REFERENCES public.products_productvariant(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

\unrestrict gXJ3tiWlPMaYV9DZIKmD6l84xoB37yCuYCSLYJzc7NduxdhUiwXo9Sbixm1IAzp

