# Generated by Django 6.1.1 on 2026-09-15 10:37

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text='Unique coupon code (case-insensitive in validation).', max_length=50, unique=True)),
                ('description', models.TextField(blank=True, default='', help_text='Optional description or promotion terms.')),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage (%)'), ('fixed', 'Fixed Amount (₹)')], default='percentage', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='Percentage value (e.g. 20 for 20%) or fixed amount in ₹.', max_digits=10)),
                ('minimum_order_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Minimum cart subtotal required to use this coupon.', max_digits=10)),
                ('maximum_discount_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum discount cap (useful for percentage discounts).', max_digits=10, null=True)),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now, help_text='Start of validity period.')),
                ('valid_until', models.DateTimeField(help_text='End of validity period.')),
                ('usage_limit', models.PositiveIntegerField(blank=True, help_text='Total maximum allowed successful uses across all users. Leave blank for unlimited.', null=True)),
                ('used_count', models.PositiveIntegerField(default=0, help_text='Actual count of successful orders placed with this coupon.')),
                ('per_user_limit', models.PositiveIntegerField(blank=True, default=1, help_text='Maximum allowed successful uses per individual user. Leave blank for unlimited.', null=True)),
                ('weekly_user_limit', models.PositiveIntegerField(default=5, help_text='Maximum allowed successful uses per individual user per week.')),
                ('is_active', models.BooleanField(default=True, help_text='Master toggle to activate or deactivate this coupon.')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Coupon',
                'verbose_name_plural': 'Coupons',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CouponConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekly_user_limit', models.PositiveIntegerField(default=5, help_text='Maximum successful coupon uses allowed per registered user per week (Mon 00:00 to Sun 23:59:59).', verbose_name='Weekly user coupon limit')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Coupon Configuration',
                'verbose_name_plural': 'Coupon Configuration',
            },
        ),
        migrations.CreateModel(
            name='CouponUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_amount', models.DecimalField(decimal_places=2, help_text='Discount amount granted on this order.', max_digits=10)),
                ('used_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Time of successful coupon usage, used for weekly limit calculations.')),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usages', to='coupons.coupon')),
            ],
            options={
                'verbose_name': 'Coupon Usage',
                'verbose_name_plural': 'Coupon Usages',
                'ordering': ['-used_at'],
            },
        ),
    ]
