# Generated by Django 6.1.1 on 2026-09-15 10:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coupons', '0001_initial'),
        ('order', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='couponusage',
            name='order',
            field=models.OneToOneField(help_text='The completed order this coupon usage belongs to. Unique to prevent duplicate records.', on_delete=django.db.models.deletion.CASCADE, related_name='coupon_usage', to='order.order'),
        ),
        migrations.AddField(
            model_name='couponusage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupon_usages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='couponusage',
            index=models.Index(fields=['user', 'used_at'], name='idx_user_used_at'),
        ),
        migrations.AddIndex(
            model_name='couponusage',
            index=models.Index(fields=['coupon', 'user'], name='idx_coupon_user'),
        ),
    ]
